- Refresh   patches.drivers/0001-badblocks-add-core-badblock-management-code.patch. - Refresh   patches.drivers/0011-irq_poll-make-blk-iopoll-available-outside-the-block-layer.patch.
Fix build breakage when building partway through series:
  CC [M]  drivers/net/ethernet/mellanox/mlx4/cmd.o
In file included from include/rdma/ib_mad.h:42:0,
		 from include/rdma/ib_smi.h:40,
		 from drivers/net/ethernet/mellanox/mlx4/cmd.c:44:
include/rdma/ib_verbs.h:52:28: fatal error: linux/irq_poll.h: No such file or directory
 #include <linux/irq_poll.h>
			    ^
compilation terminated.

irq_poll.h is introduced by
511cbce2ff8b irq_poll: make blk-iopoll available outside the block layer (v4.5-rc1)
in
patches/patches.drivers/0011-irq_poll-make-blk-iopoll-available-outside-the-block-layer.patch

suse-commit: a367b77cfe59e032b82e02db94fb785fa0f4698a