Fix multiple failures when building bnxt_re partway through the series
1)
drivers/infiniband/hw/bnxt_re/main.c:57:22: fatal error: bnxt_ulp.h: No such file or directory
 #include "bnxt_ulp.h"
                      ^
compilation terminated.
make[1]: *** [scripts/Makefile.build:259: drivers/infiniband/hw/bnxt_re/main.o] Error 1

The patches should come after the backport of
	a588e4580a7e bnxt_en: Add interface to support RDMA driver. (v4.10-rc1)

2)
In file included from include/linux/completion.h:11:0,
                 from include/linux/rcupdate.h:43,
                 from include/linux/sysctl.h:25,
                 from include/linux/timer.h:242,
                 from include/linux/workqueue.h:8,
                 from include/linux/pm.h:25,
                 from ./arch/x86/include/asm/apic.h:5,
                 from ./arch/x86/include/asm/smp.h:12,
                 from include/linux/smp.h:59,
                 from include/linux/percpu.h:6,
                 from include/linux/context_tracking_state.h:4,
                 from include/linux/vtime.h:4,
                 from include/linux/hardirq.h:7,
                 from include/linux/interrupt.h:12,
                 from drivers/infiniband/hw/bnxt_re/qplib_rcfw.c:38:
drivers/infiniband/hw/bnxt_re/qplib_rcfw.c: In function ‘bnxt_qplib_rcfw_wait_for_resp’:
include/linux/wait.h:363:9: error: ‘TASK_UNINTERRUPTIBLE’ undeclared (first use in this function)
         TASK_UNINTERRUPTIBLE, 0, timeout,   \
         ^

bnxt_re doesn't build until
patches.fixes/02-ratelimit-extend-to-print-suppressed-messages-on-release.patch
is applied, because of the following change in the latter:
+++ b/include/linux/ratelimit.h
@@ -2,11 +2,15 @@
 #define _LINUX_RATELIMIT_H

 #include <linux/param.h>
+#include <linux/sched.h>

Upstream,
6b1d174b0c27 ratelimit: extend to print suppressed messages on release (v4.8-rc1)
comes before
1ac5a4047975 RDMA/bnxt_re: Add bnxt_re RoCE driver (v4.11-rc1)
Move the ratelimit patches up in the series.

suse-commit: 45efe950dcc8c87d1168a074c53e105bfa3978b2