Refresh patches.arch/s390-sles11sp3-16-06-pci-stub.patch.
Fix a build failure in mlx4 due to the pci stubs:
drivers/infiniband/hw/mlx4/mad.c:833: error: implicit declaration of function
'kmalloc'

suse-commit: da8dc788f452bdfeb0870478aaf39d288eb1e3e1